<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.12 setup script
 * Date: Wed, 25 Mar 2015 21:38:02 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: Pulse [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Pulse';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '55131c9c849293.85738457';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>