<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.3.12 setup script
 * Date: Tue, 24 Mar 2015 22:31:38 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: pulsedb.cyfneopdwxp8.us-west-2.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'pulsedb.cyfneopdwxp8.us-west-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5511d7a75cb2c7.54826694';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>